name: gem_code
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5
  - pytorch-cuda=12.1
  - rdkit
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - pyyaml
  - setuptools>=64
  - pip
  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - optuna
      - pytorch-lightning
      - torch-geometric
      - torchmetrics
      - tqdm
      - fcd-torch
      - -e .
