batch_size: 1024
lr: 0.0002
clip_grad: null
num_workers: 0
ema_decay: 0.0
ema_use_for_eval: false
weight_decay: 0.
optimizer: adamw
seed: 0
override_optimizer_lr_on_resume: false
init_use_ema: false
dl_beta_prop: null
dl_beta_mh: null
dl_beta_mh_init: null
dl_beta_mh_final: null
dl_beta_mh_anneal_steps: null
cl_clip_mode: batch
cl_bad_negative_weight: 1.0
recovery_save_every: 0
